name: Express CD

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        # registry: ccc-testcicd.example.com
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        provenance: false   # 👈 💥 必须加在这里！！！(属于 Build and push 步骤)
        # 💥 修改点 1：打上两个标签！一个是 latest，一个是 GitHub 本次运行的唯一 ID
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/express-app:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/express-app:${{ github.run_id }}
        
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        # 💥 修改点 2：把唯一 ID 作为环境变量传给脚本
        envs: GITHUB_RUN_ID
        script: |
          cd /opt/express-app
          
          # 告诉 docker-compose，本次我们要部署的版本号是这个唯一 ID
          export IMAGE_TAG=$GITHUB_RUN_ID
          
          # 拉取最新的唯一版本（镜像源无法缓存，被迫拉取最新）
          docker-compose pull
          
          # 重启容器，移除不再使用的旧镜像
          docker-compose up -d --remove-orphans
